### ISSUE TITLE
GMW Refactoring discussion

### ISSUE THREAD

**Issue by Alendri** [allbin/google-maps-wrapper#10]
Is it possible to refactor some of the code?
Make it compliant with allbin-eslint-config?
Put everything in a Namespace?
What functions are actually required and what should be handled by the host-project?
Can we use GeoJson for everything and thereby cut down on the number of code-paths there are? (This will lead to some possibly large overhead and GC due to force creation of GeoJson-feature-objects for everything that doesn't need it today.)
General code-structure improvements maybe?

**Comment by mdjarv** [comment]
Book a meeting to discuss questions above
